server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /products {
        proxy_pass http://product-service:3002/;
    }

    location /order {
        proxy_pass http://order-service:3000/;
    }
}